### ISSUE TITLE
Running the example_cong file

### ISSUE THREAD

**Issue by adityauser** [ADGEfficiency/energy-py#53]
Hi,
After running the following command:
`energypy-experiment energypy/examples/example_config.yaml battery`
I'm getting the following Traceback:
```
Traceback (most recent call last):
  File "/home/aditya/anaconda3/envs/erg-rl/bin/energypy-experiment", line 33, in <module>
    sys.exit(load_entry_point('energypy==0.3.0', 'console_scripts', 'energypy-experiment')())
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/energypy-0.3.0-py3.6.egg/energypy/experiments/cli.py", line 22, in cli
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/energypy-0.3.0-py3.6.egg/energypy/experiments/analysis.py", line 40, in analyze_experiment
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1290, in subplots
    gridspec_kw=gridspec_kw)
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/matplotlib/figure.py", line 1522, in subplots
    return (self.add_gridspec(nrows, ncols, figure=self, **gridspec_kw)
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/matplotlib/figure.py", line 2804, in add_gridspec
    gs = GridSpec(nrows=nrows, ncols=ncols, figure=self, **kwargs)
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/matplotlib/gridspec.py", line 422, in __init__
    height_ratios=height_ratios)
  File "/home/aditya/anaconda3/envs/erg-rl/lib/python3.6/site-packages/matplotlib/gridspec.py", line 49, in __init__
    f"Number of rows must be a positive integer, not {nrows}")
ValueError: Number of rows must be a positive integer, not 0
```

Any help would be appreciated.

**Comment by ADGEfficiency** [comment]
See https://github.com/ADGEfficiency/energy-py/issues/67
